### PR TITLE
feat: store env variables in .env file

### PR DESCRIPTION
**Pull request by geekyahmed**
Storing the environment variables in a .env file is a much better way for storing most of the sensitive information. This PR also contains a proper documentation on how to set up the ```env``` file with the ```.env.example ``` file.

Just in case we decide to move to a much bigger project structure and store our secret/private keys without having to mess with the production server

### CODE REVIEW

**Comment by ivelin** [comment]
Thank you for the contribution, @geekyahmed . I will review this PR and get back to you shortly.

**Comment by geekyahmed** [comment]
That will be really awesome @ivelin

**Comment by ivelin** [comment]
What do you think about using package.json for these config parameters to minimize the external OS specific dependencies?

**Comment by geekyahmed** [comment]
True!

Don't you think it will become a problem if we needed to add more config parameters when the app gets much  bigger ?

**Comment by ivelin** [comment]
> True!
> 
> Don't you think it will become a problem if we needed to add more config parameters when the app gets much bigger ?

package.json is already good size, but that's still the typical way for configuring js apps, no?

**Comment by geekyahmed** [comment]
Well, it depends on how the app will grow and scale

**Comment by ivelin** [comment]
Let's review this PR again as the app grows and it needs easier configuration.

**Pull request closed without merging**
